// <auto-generated />
using Expediente_RASE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Expediente_RASE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211110035405_Usuarios")]
    partial class Usuarios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Expediente_RASE.Models.T_USUARIOS", b =>
                {
                    b.Property<string>("ID_USER")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CARGO_U")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTRA_U")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CORREO_U")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_USER");

                    b.ToTable("USUARIOS");
                });
#pragma warning restore 612, 618
        }
    }
}
